# 其他配置
application:
  baseDirectory: /Users/zhangxin/Documents/work_space/temp_file/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/publish?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: root
    password:
    hikari:
      maximum-pool-size: 10
      max-lifetime: 30000
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:${application.baseDirectory}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.hotstrip.publish.model

# pagehelper
pagehelper:
  reasonable: true
  row-bounds-with-count: true

# log
logging:
  config: classpath:logback.xml

server:
  servlet:
    context-path: /publish/